export * from './address.service';
import { AddressService } from './address.service';
export * from './area.service';
import { AreaService } from './area.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './bag.service';
import { BagService } from './bag.service';
export * from './cell.service';
import { CellService } from './cell.service';
export * from './cellMember.service';
import { CellMemberService } from './cellMember.service';
export * from './children.service';
import { ChildrenService } from './children.service';
export * from './eventLine.service';
import { EventLineService } from './eventLine.service';
export * from './menu.service';
import { MenuService } from './menu.service';
export * from './ministry.service';
import { MinistryService } from './ministry.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AddressService, AreaService, AuthService, BagService, CellService, CellMemberService, ChildrenService, EventLineService, MenuService, MinistryService, PaymentService, ProductService, UserService];
