/**
 * O Alvo API - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Payment } from './payment';
import { Product } from './product';
import { User } from './user';

export class Bag { 
    code?: string;
    openAt?: string;
    customer?: User;
    status?: string;
    products?: Array<Product>;
    payment?: Payment;
    shipping?: Address;
}