/**
 * O Alvo API - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Area } from './area';
import { User } from './user';

export class Cell { 
    name?: string;
    area?: Area;
    leaders?: Array<User>;
    shepherds?: Array<User>;
    secretaries?: Array<User>;
    schedule?: string;
    day?: string;
    type?: string;
    status?: string;
    address?: Address;
    branch?: string;
}