/**
 * O Alvo API - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventLine } from './eventLine';
import { User } from './user';

export class Children { 
    name?: string;
    document?: string;
    birthday?: string;
    area?: string;
    parents?: Array<User>;
    contact?: Array<number>;
    events?: Array<EventLine>;
    type?: string;
    status?: string;
    createAt?: Date;
    updateAt?: Date;
}