/**
 * O Alvo API - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class EventLine { 
    title?: string;
    startDate?: string;
    endDate?: string;
    type?: string;
    amount?: number;
    status?: string;
    description?: string;
    locale?: string;
    createdAt?: Date;
    updateAt?: Date;
}