/**
 * Tzion API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Area } from './area';
import { Cell } from './cell';
import { Menu } from './menu';
import { Ministry } from './ministry';

export class User { 
    name?: string;
    age?: number;
    birthday?: string;
    email?: string;
    document?: string;
    type?: string;
    password?: string;
    address?: any;
    status?: string;
    ministries?: any;
    area?: Area;
    cells?: any;
    menu?: Array<any>;
    createdAt?: string;
    deletedAt?: string;
    updatedAt?: string;
}